name: Export for Android and iOS
on:
  workflow_run:
    workflows: [ "Build Android" ]
    types: 
      - completed
  push:
    paths: 
      - '.github/workflows/export_android_ios_project.yml'
      - 'example/**'
    branches: [ master ]
jobs:
  export:
    name: Export and Upload Artifact
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GODOT_VERSIONS: [3.3]
    steps:
    - uses: actions/checkout@v2

    - name: Downloading templates 
      run: |
        wget -nv https://downloads.tuxfamily.org/godotengine/${{matrix.GODOT_VERSIONS}}/Godot_v${{matrix.GODOT_VERSIONS}}-stable_export_templates.tpz 

    - name: Install Android Build Template
      run: |
        mkdir -v -p build/android
        unzip Godot_v${{matrix.GODOT_VERSIONS}}-stable_export_templates.tpz
        wget -nv https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/releases/download/Android_v3.2.2%2B/android-standard-template-v${{matrix.GODOT_VERSIONS}}.zip
        mkdir example/android
        mkdir example/android/plugins
        mkdir example/android/build
        echo "${{matrix.GODOT_VERSIONS}}.stable" >> example/android/.build_version
        unzip android-template-v${{matrix.GODOT_VERSIONS}}.zip -d example/android/plugins
        unzip templates/android_source.zip -d example/android/build
 
    - name: Change AndroidManifest.xml, move ADB and debug.keystore to /usr/bin path
      run: |
        cd example/android/build
        sudo apt-get install -y xmlstarlet
        xmlstarlet ed --subnode "/manifest/application" --type elem -n meta-data -v "" AndroidManifest.xml | \
        xmlstarlet ed --insert "/manifest/application/meta-data[last()]" --type attr -n android:name -v com.google.android.gms.ads.APPLICATION_ID | \
        xmlstarlet ed --insert "/manifest/application/meta-data[last()]" --type attr -n android:value -v ca-app-pub-3940256099942544~3347511713 > output.xml
        mv output.xml AndroidManifest.xml
        cat AndroidManifest.xml

        keytool -keyalg RSA -genkeypair -alias androiddebugkey -keypass android -keystore debug.keystore -storepass android -dname "CN=Android Debug,O=Android,C=US" -validity 9999 -deststoretype pkcs12
        sudo chmod 777 -R /usr/bin
        mv debug.keystore /usr/bin
        mv /usr/local/lib/android/sdk/platform-tools/adb /usr/bin
        cd /usr/bin
        ls


    - name: Export AdMob example to Android and iOS
      # Use latest version (see releases for all versions)
      uses: gustavottc/godot-export@master
      with:
        # Defining all the required inputs
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/${{matrix.GODOT_VERSIONS}}/Godot_v${{matrix.GODOT_VERSIONS}}-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/${{matrix.GODOT_VERSIONS}}/Godot_v${{matrix.GODOT_VERSIONS}}-stable_export_templates.tpz
        relative_project_path: ./example/
        use_preset_export_path: true
        create_release: false
        export_debug: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - name: Download ios-template from iOS Tag and rename .a file by ios-template downloaded
      run: |
        cd ../builds/ios/iOS
        wget "https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/releases/download/iOS_v3.3%2B/ios-template-v${{matrix.GODOT_VERSIONS}}.zip"
        unzip ios-template-v${{matrix.GODOT_VERSIONS}}.zip
        rm ios-template-v${{matrix.GODOT_VERSIONS}}.zip
        mv libgodot.iphone.release.fat.a AdMob.a 
        ls


    - name: Upload iOS artifact
      uses: actions/upload-artifact@v2
      with:
        name: AdMobiOS
        path: /home/runner/work/Godot-AdMob-Android-iOS/builds/ios/iOS/

    - name: Upload Android artifact
      uses: actions/upload-artifact@v2
      with:
        name: AdMobAndroid
        path: /home/runner/work/Godot-AdMob-Android-iOS/builds/android/Android/

  
