name: Build Android

on:
  push:
    paths: 
      - '.github/workflows/release_android_v3_2_2*.yml'
      - 'android/**'
    branches: [ master ]
  pull_request:
    paths: 
      - 'android/**'
    branches: [ master ]

env:
  TAG_NAME: Android_v3.2.2+
  RELEASE_NAME: Android Compiled files for v3.2.2+

jobs:
  android-template:
    name: Compiling Gradle (Android)
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        RELEASE_VERSIONS: ["standard", "mono"]
        GODOT_VERSIONS: [3.2.2, 3.2.3, 3.3]

    steps:
    - uses: actions/checkout@v2

    # Github Actions Matrix doesnt support x.0 values, it's replaced by ''
    - name: Verify current matrix's GODOT_VERSIONS
      run: |
        CURRENT_GODOT_VERSION=${{matrix.GODOT_VERSIONS}}
        if [ ${#CURRENT_GODOT_VERSION} -eq 1 ]; then CURRENT_GODOT_VERSION="${CURRENT_GODOT_VERSION}.0"; fi
        echo "CURRENT_GODOT_VERSION=${CURRENT_GODOT_VERSION}" >> $GITHUB_ENV

    - name: Download and prepare the Stable Godot .AAR LIB
      run: | 
        cd android/admob/godot-lib 
        GODOT_AAR_LIB="godot-lib.aar"
        if [ ${{matrix.RELEASE_VERSIONS}} = standard ]; then 
          GODOT_AAR_FILENAME="godot-lib.${{env.CURRENT_GODOT_VERSION}}.stable.release.aar"
          FULL_PATHNAME_DOWNLOAD_GODOT_AAR="https://downloads.tuxfamily.org/godotengine/${{env.CURRENT_GODOT_VERSION}}/${GODOT_AAR_FILENAME}"
        elif [ ${{matrix.RELEASE_VERSIONS}} = mono ]; then 
          GODOT_AAR_FILENAME="godot-lib.${{env.CURRENT_GODOT_VERSION}}.stable.mono.release.aar"
          FULL_PATHNAME_DOWNLOAD_GODOT_AAR="https://downloads.tuxfamily.org/godotengine/${{env.CURRENT_GODOT_VERSION}}/mono/${GODOT_AAR_FILENAME}"
        fi

        #get file on Godot's server and rename
        wget $FULL_PATHNAME_DOWNLOAD_GODOT_AAR
        mv $GODOT_AAR_FILENAME $GODOT_AAR_LIB
    
    - name: Grant execute permission for gradlew
      run: |
        cd android/admob
        chmod +x gradlew
        
    - name: Build with Gradle
      run: | 
        cd android/admob
        ./gradlew build

    - name: Compress the binaries
      run: |
        zip -j android-${{matrix.RELEASE_VERSIONS}}-template-v${{env.CURRENT_GODOT_VERSION}}.zip android/admob/admob/build/outputs/aar/*

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: android-${{matrix.RELEASE_VERSIONS}}-template-v${{env.CURRENT_GODOT_VERSION}}.zip
        path: android-${{matrix.RELEASE_VERSIONS}}-template-v${{env.CURRENT_GODOT_VERSION}}.zip

  upload-assets-release:
    needs: [android-template]
    name: Upload assets to release
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      
    - name: Delete previous tag
      uses: dev-drprasad/delete-tag-and-release@v0.1.2
      with:
        delete_release: true 
        tag_name: ${{env.TAG_NAME}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release and tag
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{env.TAG_NAME}}
        release_name: ${{env.RELEASE_NAME}}
    
    - name: Upload artifacts to release
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'android-template-*.zip/*'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: ${{env.TAG_NAME}}
